/**
 * Copyright (c) 2013-2022, Alibaba Group Holding Limited;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * </p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.alibaba.polardbx.rpc.cdc;

public final class DumperServer {
  private DumperServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowBinlogEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowBinlogEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_DumpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_DumpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_BinaryLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_BinaryLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_FullBinaryLog_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_FullBinaryLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_MasterStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_MasterStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_FullMasterStatus_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_FullMasterStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_BinlogEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_BinlogEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_DumpStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_DumpStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_RplCommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_RplCommandResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ChangeMasterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ChangeMasterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_StartSlaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_StartSlaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_StopSlaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_StopSlaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ResetSlaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ResetSlaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ChangeReplicationFilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ChangeReplicationFilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowSlaveStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowSlaveStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowSlaveStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowSlaveStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DumperServer.proto\022\006dumper\"F\n\007Request\022" +
      "\013\n\003req\030\001 \001(\t\022\022\n\nstreamName\030\002 \001(\t\022\032\n\022excl" +
      "udeRemoteFiles\030\003 \001(\010\"m\n\027ShowBinlogEvents" +
      "Request\022\017\n\007logName\030\001 \001(\t\022\013\n\003pos\030\002 \001(\003\022\016\n" +
      "\006offset\030\003 \001(\003\022\020\n\010rowCount\030\004 \001(\003\022\022\n\nstrea" +
      "mName\030\005 \001(\t\"\221\001\n\013DumpRequest\022\020\n\010fileName\030" +
      "\001 \001(\t\022\020\n\010position\030\002 \001(\003\022)\n\tsplitMode\030\003 \001" +
      "(\0162\026.dumper.EventSplitMode\022\022\n\nregistered" +
      "\030\004 \001(\010\022\013\n\003ext\030\005 \001(\t\022\022\n\nstreamName\030\006 \001(\t\"" +
      ".\n\tBinaryLog\022\017\n\007logName\030\001 \001(\t\022\020\n\010fileSiz" +
      "e\030\002 \001(\003\"\330\001\n\rFullBinaryLog\022\017\n\007logName\030\001 \001" +
      "(\t\022\020\n\010fileSize\030\002 \001(\003\022\023\n\013createdTime\030\003 \001(" +
      "\t\022\026\n\016lastModifyTime\030\004 \001(\t\022\026\n\016firstEventT" +
      "ime\030\005 \001(\t\022\025\n\rlastEventTime\030\006 \001(\t\022\017\n\007last" +
      "Tso\030\007 \001(\t\022\024\n\014uploadStatus\030\010 \001(\t\022\024\n\014fileL" +
      "ocation\030\t \001(\t\022\013\n\003ext\030\n \001(\t\"s\n\014MasterStat" +
      "us\022\014\n\004file\030\001 \001(\t\022\020\n\010position\030\002 \001(\003\022\022\n\nbi" +
      "nlogDoDB\030\003 \001(\t\022\026\n\016binlogIgnoreDB\030\004 \001(\t\022\027" +
      "\n\017executedGtidSet\030\005 \001(\t\"\366\001\n\020FullMasterSt" +
      "atus\022\014\n\004file\030\001 \001(\t\022\020\n\010position\030\002 \001(\003\022\017\n\007" +
      "lastTso\030\003 \001(\t\022\021\n\tdelayTime\030\004 \001(\003\022\021\n\tavgR" +
      "evEps\030\005 \001(\003\022\021\n\tavgRevBps\030\006 \001(\003\022\023\n\013avgWri" +
      "teEps\030\007 \001(\003\022\023\n\013avgWriteBps\030\010 \001(\003\022\023\n\013avgW" +
      "riteTps\030\t \001(\003\022\024\n\014avgUploadBps\030\n \001(\003\022\022\n\na" +
      "vgDumpBps\030\013 \001(\003\022\017\n\007extInfo\030\014 \001(\t\"q\n\013Binl" +
      "ogEvent\022\017\n\007logName\030\001 \001(\t\022\013\n\003pos\030\002 \001(\003\022\021\n" +
      "\teventType\030\003 \001(\t\022\020\n\010serverId\030\004 \001(\003\022\021\n\ten" +
      "dLogPos\030\005 \001(\003\022\014\n\004info\030\006 \001(\t\"2\n\nDumpStrea" +
      "m\022\017\n\007payload\030\001 \001(\014\022\023\n\013isHeartBeat\030\002 \001(\010\"" +
      "7\n\022RplCommandResponse\022\022\n\nresultCode\030\001 \001(" +
      "\005\022\r\n\005error\030\002 \001(\t\"&\n\023ChangeMasterRequest\022" +
      "\017\n\007request\030\001 \001(\t\"$\n\021StartSlaveRequest\022\017\n" +
      "\007request\030\001 \001(\t\"#\n\020StopSlaveRequest\022\017\n\007re" +
      "quest\030\001 \001(\t\"$\n\021ResetSlaveRequest\022\017\n\007requ" +
      "est\030\001 \001(\t\"1\n\036ChangeReplicationFilterRequ" +
      "est\022\017\n\007request\030\001 \001(\t\")\n\026ShowSlaveStatusR" +
      "equest\022\017\n\007request\030\001 \001(\t\"+\n\027ShowSlaveStat" +
      "usResponse\022\020\n\010response\030\001 \001(\t*4\n\016EventSpl" +
      "itMode\022\n\n\006SERVER\020\000\022\n\n\006CLIENT\020\001\022\n\n\006RANDOM" +
      "\020\0022\231\007\n\nCdcService\0228\n\016ShowBinaryLogs\022\017.du" +
      "mper.Request\032\021.dumper.BinaryLog\"\0000\001\022@\n\022S" +
      "howFullBinaryLogs\022\017.dumper.Request\032\025.dum" +
      "per.FullBinaryLog\"\0000\001\022;\n\020ShowMasterStatu" +
      "s\022\017.dumper.Request\032\024.dumper.MasterStatus" +
      "\"\000\022C\n\024ShowFullMasterStatus\022\017.dumper.Requ" +
      "est\032\030.dumper.FullMasterStatus\"\000\022L\n\020ShowB" +
      "inlogEvents\022\037.dumper.ShowBinlogEventsReq" +
      "uest\032\023.dumper.BinlogEvent\"\0000\001\0223\n\004Dump\022\023." +
      "dumper.DumpRequest\032\022.dumper.DumpStream\"\000" +
      "0\001\0223\n\004Sync\022\023.dumper.DumpRequest\032\022.dumper" +
      ".DumpStream\"\0000\001\022I\n\014ChangeMaster\022\033.dumper" +
      ".ChangeMasterRequest\032\032.dumper.RplCommand" +
      "Response\"\000\022_\n\027ChangeReplicationFilter\022&." +
      "dumper.ChangeReplicationFilterRequest\032\032." +
      "dumper.RplCommandResponse\"\000\022E\n\nStartSlav" +
      "e\022\031.dumper.StartSlaveRequest\032\032.dumper.Rp" +
      "lCommandResponse\"\000\022C\n\tStopSlave\022\030.dumper" +
      ".StopSlaveRequest\032\032.dumper.RplCommandRes" +
      "ponse\"\000\022E\n\nResetSlave\022\031.dumper.ResetSlav" +
      "eRequest\032\032.dumper.RplCommandResponse\"\000\022V" +
      "\n\017ShowSlaveStatus\022\036.dumper.ShowSlaveStat" +
      "usRequest\032\037.dumper.ShowSlaveStatusRespon" +
      "se\"\0000\001B\"\n\034com.alibaba.polardbx.rpc.cdcH\001" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dumper_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dumper_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_Request_descriptor,
        new java.lang.String[] { "Req", "StreamName", "ExcludeRemoteFiles", });
    internal_static_dumper_ShowBinlogEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dumper_ShowBinlogEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowBinlogEventsRequest_descriptor,
        new java.lang.String[] { "LogName", "Pos", "Offset", "RowCount", "StreamName", });
    internal_static_dumper_DumpRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dumper_DumpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_DumpRequest_descriptor,
        new java.lang.String[] { "FileName", "Position", "SplitMode", "Registered", "Ext", "StreamName", });
    internal_static_dumper_BinaryLog_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dumper_BinaryLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_BinaryLog_descriptor,
        new java.lang.String[] { "LogName", "FileSize", });
    internal_static_dumper_FullBinaryLog_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dumper_FullBinaryLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_FullBinaryLog_descriptor,
        new java.lang.String[] { "LogName", "FileSize", "CreatedTime", "LastModifyTime", "FirstEventTime", "LastEventTime", "LastTso", "UploadStatus", "FileLocation", "Ext", });
    internal_static_dumper_MasterStatus_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_dumper_MasterStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_MasterStatus_descriptor,
        new java.lang.String[] { "File", "Position", "BinlogDoDB", "BinlogIgnoreDB", "ExecutedGtidSet", });
    internal_static_dumper_FullMasterStatus_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_dumper_FullMasterStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_FullMasterStatus_descriptor,
        new java.lang.String[] { "File", "Position", "LastTso", "DelayTime", "AvgRevEps", "AvgRevBps", "AvgWriteEps", "AvgWriteBps", "AvgWriteTps", "AvgUploadBps", "AvgDumpBps", "ExtInfo", });
    internal_static_dumper_BinlogEvent_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_dumper_BinlogEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_BinlogEvent_descriptor,
        new java.lang.String[] { "LogName", "Pos", "EventType", "ServerId", "EndLogPos", "Info", });
    internal_static_dumper_DumpStream_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_dumper_DumpStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_DumpStream_descriptor,
        new java.lang.String[] { "Payload", "IsHeartBeat", });
    internal_static_dumper_RplCommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_dumper_RplCommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_RplCommandResponse_descriptor,
        new java.lang.String[] { "ResultCode", "Error", });
    internal_static_dumper_ChangeMasterRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_dumper_ChangeMasterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ChangeMasterRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_StartSlaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_dumper_StartSlaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_StartSlaveRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_StopSlaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_dumper_StopSlaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_StopSlaveRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ResetSlaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_dumper_ResetSlaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ResetSlaveRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ChangeReplicationFilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_dumper_ChangeReplicationFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ChangeReplicationFilterRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ShowSlaveStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_dumper_ShowSlaveStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowSlaveStatusRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ShowSlaveStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_dumper_ShowSlaveStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowSlaveStatusResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
