/**
 * Copyright (c) 2013-2022, Alibaba Group Holding Limited;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * </p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.alibaba.polardbx.rpc.cdc;

/**
 * Protobuf type {@code dumper.FullMasterStatus}
 */
public final class FullMasterStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dumper.FullMasterStatus)
    FullMasterStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FullMasterStatus.newBuilder() to construct.
  private FullMasterStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FullMasterStatus() {
    file_ = "";
    lastTso_ = "";
    extInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FullMasterStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FullMasterStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            file_ = s;
            break;
          }
          case 16: {

            position_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lastTso_ = s;
            break;
          }
          case 32: {

            delayTime_ = input.readInt64();
            break;
          }
          case 40: {

            avgRevEps_ = input.readInt64();
            break;
          }
          case 48: {

            avgRevBps_ = input.readInt64();
            break;
          }
          case 56: {

            avgWriteEps_ = input.readInt64();
            break;
          }
          case 64: {

            avgWriteBps_ = input.readInt64();
            break;
          }
          case 72: {

            avgWriteTps_ = input.readInt64();
            break;
          }
          case 80: {

            avgUploadBps_ = input.readInt64();
            break;
          }
          case 88: {

            avgDumpBps_ = input.readInt64();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            extInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alibaba.polardbx.rpc.cdc.DumperServer.internal_static_dumper_FullMasterStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alibaba.polardbx.rpc.cdc.DumperServer.internal_static_dumper_FullMasterStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alibaba.polardbx.rpc.cdc.FullMasterStatus.class, com.alibaba.polardbx.rpc.cdc.FullMasterStatus.Builder.class);
  }

  public static final int FILE_FIELD_NUMBER = 1;
  private volatile java.lang.Object file_;
  /**
   * <code>string file = 1;</code>
   * @return The file.
   */
  @java.lang.Override
  public java.lang.String getFile() {
    java.lang.Object ref = file_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      file_ = s;
      return s;
    }
  }
  /**
   * <code>string file = 1;</code>
   * @return The bytes for file.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileBytes() {
    java.lang.Object ref = file_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      file_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private long position_;
  /**
   * <code>int64 position = 2;</code>
   * @return The position.
   */
  @java.lang.Override
  public long getPosition() {
    return position_;
  }

  public static final int LASTTSO_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastTso_;
  /**
   * <code>string lastTso = 3;</code>
   * @return The lastTso.
   */
  @java.lang.Override
  public java.lang.String getLastTso() {
    java.lang.Object ref = lastTso_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastTso_ = s;
      return s;
    }
  }
  /**
   * <code>string lastTso = 3;</code>
   * @return The bytes for lastTso.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastTsoBytes() {
    java.lang.Object ref = lastTso_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastTso_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELAYTIME_FIELD_NUMBER = 4;
  private long delayTime_;
  /**
   * <code>int64 delayTime = 4;</code>
   * @return The delayTime.
   */
  @java.lang.Override
  public long getDelayTime() {
    return delayTime_;
  }

  public static final int AVGREVEPS_FIELD_NUMBER = 5;
  private long avgRevEps_;
  /**
   * <code>int64 avgRevEps = 5;</code>
   * @return The avgRevEps.
   */
  @java.lang.Override
  public long getAvgRevEps() {
    return avgRevEps_;
  }

  public static final int AVGREVBPS_FIELD_NUMBER = 6;
  private long avgRevBps_;
  /**
   * <code>int64 avgRevBps = 6;</code>
   * @return The avgRevBps.
   */
  @java.lang.Override
  public long getAvgRevBps() {
    return avgRevBps_;
  }

  public static final int AVGWRITEEPS_FIELD_NUMBER = 7;
  private long avgWriteEps_;
  /**
   * <code>int64 avgWriteEps = 7;</code>
   * @return The avgWriteEps.
   */
  @java.lang.Override
  public long getAvgWriteEps() {
    return avgWriteEps_;
  }

  public static final int AVGWRITEBPS_FIELD_NUMBER = 8;
  private long avgWriteBps_;
  /**
   * <code>int64 avgWriteBps = 8;</code>
   * @return The avgWriteBps.
   */
  @java.lang.Override
  public long getAvgWriteBps() {
    return avgWriteBps_;
  }

  public static final int AVGWRITETPS_FIELD_NUMBER = 9;
  private long avgWriteTps_;
  /**
   * <code>int64 avgWriteTps = 9;</code>
   * @return The avgWriteTps.
   */
  @java.lang.Override
  public long getAvgWriteTps() {
    return avgWriteTps_;
  }

  public static final int AVGUPLOADBPS_FIELD_NUMBER = 10;
  private long avgUploadBps_;
  /**
   * <code>int64 avgUploadBps = 10;</code>
   * @return The avgUploadBps.
   */
  @java.lang.Override
  public long getAvgUploadBps() {
    return avgUploadBps_;
  }

  public static final int AVGDUMPBPS_FIELD_NUMBER = 11;
  private long avgDumpBps_;
  /**
   * <code>int64 avgDumpBps = 11;</code>
   * @return The avgDumpBps.
   */
  @java.lang.Override
  public long getAvgDumpBps() {
    return avgDumpBps_;
  }

  public static final int EXTINFO_FIELD_NUMBER = 12;
  private volatile java.lang.Object extInfo_;
  /**
   * <code>string extInfo = 12;</code>
   * @return The extInfo.
   */
  @java.lang.Override
  public java.lang.String getExtInfo() {
    java.lang.Object ref = extInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string extInfo = 12;</code>
   * @return The bytes for extInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtInfoBytes() {
    java.lang.Object ref = extInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, file_);
    }
    if (position_ != 0L) {
      output.writeInt64(2, position_);
    }
    if (!getLastTsoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastTso_);
    }
    if (delayTime_ != 0L) {
      output.writeInt64(4, delayTime_);
    }
    if (avgRevEps_ != 0L) {
      output.writeInt64(5, avgRevEps_);
    }
    if (avgRevBps_ != 0L) {
      output.writeInt64(6, avgRevBps_);
    }
    if (avgWriteEps_ != 0L) {
      output.writeInt64(7, avgWriteEps_);
    }
    if (avgWriteBps_ != 0L) {
      output.writeInt64(8, avgWriteBps_);
    }
    if (avgWriteTps_ != 0L) {
      output.writeInt64(9, avgWriteTps_);
    }
    if (avgUploadBps_ != 0L) {
      output.writeInt64(10, avgUploadBps_);
    }
    if (avgDumpBps_ != 0L) {
      output.writeInt64(11, avgDumpBps_);
    }
    if (!getExtInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, extInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, file_);
    }
    if (position_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, position_);
    }
    if (!getLastTsoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastTso_);
    }
    if (delayTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, delayTime_);
    }
    if (avgRevEps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, avgRevEps_);
    }
    if (avgRevBps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, avgRevBps_);
    }
    if (avgWriteEps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, avgWriteEps_);
    }
    if (avgWriteBps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, avgWriteBps_);
    }
    if (avgWriteTps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, avgWriteTps_);
    }
    if (avgUploadBps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, avgUploadBps_);
    }
    if (avgDumpBps_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, avgDumpBps_);
    }
    if (!getExtInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, extInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alibaba.polardbx.rpc.cdc.FullMasterStatus)) {
      return super.equals(obj);
    }
    com.alibaba.polardbx.rpc.cdc.FullMasterStatus other = (com.alibaba.polardbx.rpc.cdc.FullMasterStatus) obj;

    if (!getFile()
        .equals(other.getFile())) return false;
    if (getPosition()
        != other.getPosition()) return false;
    if (!getLastTso()
        .equals(other.getLastTso())) return false;
    if (getDelayTime()
        != other.getDelayTime()) return false;
    if (getAvgRevEps()
        != other.getAvgRevEps()) return false;
    if (getAvgRevBps()
        != other.getAvgRevBps()) return false;
    if (getAvgWriteEps()
        != other.getAvgWriteEps()) return false;
    if (getAvgWriteBps()
        != other.getAvgWriteBps()) return false;
    if (getAvgWriteTps()
        != other.getAvgWriteTps()) return false;
    if (getAvgUploadBps()
        != other.getAvgUploadBps()) return false;
    if (getAvgDumpBps()
        != other.getAvgDumpBps()) return false;
    if (!getExtInfo()
        .equals(other.getExtInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILE_FIELD_NUMBER;
    hash = (53 * hash) + getFile().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPosition());
    hash = (37 * hash) + LASTTSO_FIELD_NUMBER;
    hash = (53 * hash) + getLastTso().hashCode();
    hash = (37 * hash) + DELAYTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDelayTime());
    hash = (37 * hash) + AVGREVEPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgRevEps());
    hash = (37 * hash) + AVGREVBPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgRevBps());
    hash = (37 * hash) + AVGWRITEEPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgWriteEps());
    hash = (37 * hash) + AVGWRITEBPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgWriteBps());
    hash = (37 * hash) + AVGWRITETPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgWriteTps());
    hash = (37 * hash) + AVGUPLOADBPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgUploadBps());
    hash = (37 * hash) + AVGDUMPBPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvgDumpBps());
    hash = (37 * hash) + EXTINFO_FIELD_NUMBER;
    hash = (53 * hash) + getExtInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alibaba.polardbx.rpc.cdc.FullMasterStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dumper.FullMasterStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dumper.FullMasterStatus)
      com.alibaba.polardbx.rpc.cdc.FullMasterStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.polardbx.rpc.cdc.DumperServer.internal_static_dumper_FullMasterStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.polardbx.rpc.cdc.DumperServer.internal_static_dumper_FullMasterStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.polardbx.rpc.cdc.FullMasterStatus.class, com.alibaba.polardbx.rpc.cdc.FullMasterStatus.Builder.class);
    }

    // Construct using com.alibaba.polardbx.rpc.cdc.FullMasterStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      file_ = "";

      position_ = 0L;

      lastTso_ = "";

      delayTime_ = 0L;

      avgRevEps_ = 0L;

      avgRevBps_ = 0L;

      avgWriteEps_ = 0L;

      avgWriteBps_ = 0L;

      avgWriteTps_ = 0L;

      avgUploadBps_ = 0L;

      avgDumpBps_ = 0L;

      extInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alibaba.polardbx.rpc.cdc.DumperServer.internal_static_dumper_FullMasterStatus_descriptor;
    }

    @java.lang.Override
    public com.alibaba.polardbx.rpc.cdc.FullMasterStatus getDefaultInstanceForType() {
      return com.alibaba.polardbx.rpc.cdc.FullMasterStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.alibaba.polardbx.rpc.cdc.FullMasterStatus build() {
      com.alibaba.polardbx.rpc.cdc.FullMasterStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alibaba.polardbx.rpc.cdc.FullMasterStatus buildPartial() {
      com.alibaba.polardbx.rpc.cdc.FullMasterStatus result = new com.alibaba.polardbx.rpc.cdc.FullMasterStatus(this);
      result.file_ = file_;
      result.position_ = position_;
      result.lastTso_ = lastTso_;
      result.delayTime_ = delayTime_;
      result.avgRevEps_ = avgRevEps_;
      result.avgRevBps_ = avgRevBps_;
      result.avgWriteEps_ = avgWriteEps_;
      result.avgWriteBps_ = avgWriteBps_;
      result.avgWriteTps_ = avgWriteTps_;
      result.avgUploadBps_ = avgUploadBps_;
      result.avgDumpBps_ = avgDumpBps_;
      result.extInfo_ = extInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alibaba.polardbx.rpc.cdc.FullMasterStatus) {
        return mergeFrom((com.alibaba.polardbx.rpc.cdc.FullMasterStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alibaba.polardbx.rpc.cdc.FullMasterStatus other) {
      if (other == com.alibaba.polardbx.rpc.cdc.FullMasterStatus.getDefaultInstance()) return this;
      if (!other.getFile().isEmpty()) {
        file_ = other.file_;
        onChanged();
      }
      if (other.getPosition() != 0L) {
        setPosition(other.getPosition());
      }
      if (!other.getLastTso().isEmpty()) {
        lastTso_ = other.lastTso_;
        onChanged();
      }
      if (other.getDelayTime() != 0L) {
        setDelayTime(other.getDelayTime());
      }
      if (other.getAvgRevEps() != 0L) {
        setAvgRevEps(other.getAvgRevEps());
      }
      if (other.getAvgRevBps() != 0L) {
        setAvgRevBps(other.getAvgRevBps());
      }
      if (other.getAvgWriteEps() != 0L) {
        setAvgWriteEps(other.getAvgWriteEps());
      }
      if (other.getAvgWriteBps() != 0L) {
        setAvgWriteBps(other.getAvgWriteBps());
      }
      if (other.getAvgWriteTps() != 0L) {
        setAvgWriteTps(other.getAvgWriteTps());
      }
      if (other.getAvgUploadBps() != 0L) {
        setAvgUploadBps(other.getAvgUploadBps());
      }
      if (other.getAvgDumpBps() != 0L) {
        setAvgDumpBps(other.getAvgDumpBps());
      }
      if (!other.getExtInfo().isEmpty()) {
        extInfo_ = other.extInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alibaba.polardbx.rpc.cdc.FullMasterStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alibaba.polardbx.rpc.cdc.FullMasterStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object file_ = "";
    /**
     * <code>string file = 1;</code>
     * @return The file.
     */
    public java.lang.String getFile() {
      java.lang.Object ref = file_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        file_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file = 1;</code>
     * @return The bytes for file.
     */
    public com.google.protobuf.ByteString
        getFileBytes() {
      java.lang.Object ref = file_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        file_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file = 1;</code>
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      file_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFile() {
      
      file_ = getDefaultInstance().getFile();
      onChanged();
      return this;
    }
    /**
     * <code>string file = 1;</code>
     * @param value The bytes for file to set.
     * @return This builder for chaining.
     */
    public Builder setFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      file_ = value;
      onChanged();
      return this;
    }

    private long position_ ;
    /**
     * <code>int64 position = 2;</code>
     * @return The position.
     */
    @java.lang.Override
    public long getPosition() {
      return position_;
    }
    /**
     * <code>int64 position = 2;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(long value) {
      
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 position = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      
      position_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object lastTso_ = "";
    /**
     * <code>string lastTso = 3;</code>
     * @return The lastTso.
     */
    public java.lang.String getLastTso() {
      java.lang.Object ref = lastTso_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastTso_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastTso = 3;</code>
     * @return The bytes for lastTso.
     */
    public com.google.protobuf.ByteString
        getLastTsoBytes() {
      java.lang.Object ref = lastTso_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastTso_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastTso = 3;</code>
     * @param value The lastTso to set.
     * @return This builder for chaining.
     */
    public Builder setLastTso(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastTso_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastTso = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastTso() {
      
      lastTso_ = getDefaultInstance().getLastTso();
      onChanged();
      return this;
    }
    /**
     * <code>string lastTso = 3;</code>
     * @param value The bytes for lastTso to set.
     * @return This builder for chaining.
     */
    public Builder setLastTsoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastTso_ = value;
      onChanged();
      return this;
    }

    private long delayTime_ ;
    /**
     * <code>int64 delayTime = 4;</code>
     * @return The delayTime.
     */
    @java.lang.Override
    public long getDelayTime() {
      return delayTime_;
    }
    /**
     * <code>int64 delayTime = 4;</code>
     * @param value The delayTime to set.
     * @return This builder for chaining.
     */
    public Builder setDelayTime(long value) {
      
      delayTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 delayTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelayTime() {
      
      delayTime_ = 0L;
      onChanged();
      return this;
    }

    private long avgRevEps_ ;
    /**
     * <code>int64 avgRevEps = 5;</code>
     * @return The avgRevEps.
     */
    @java.lang.Override
    public long getAvgRevEps() {
      return avgRevEps_;
    }
    /**
     * <code>int64 avgRevEps = 5;</code>
     * @param value The avgRevEps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgRevEps(long value) {
      
      avgRevEps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgRevEps = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgRevEps() {
      
      avgRevEps_ = 0L;
      onChanged();
      return this;
    }

    private long avgRevBps_ ;
    /**
     * <code>int64 avgRevBps = 6;</code>
     * @return The avgRevBps.
     */
    @java.lang.Override
    public long getAvgRevBps() {
      return avgRevBps_;
    }
    /**
     * <code>int64 avgRevBps = 6;</code>
     * @param value The avgRevBps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgRevBps(long value) {
      
      avgRevBps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgRevBps = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgRevBps() {
      
      avgRevBps_ = 0L;
      onChanged();
      return this;
    }

    private long avgWriteEps_ ;
    /**
     * <code>int64 avgWriteEps = 7;</code>
     * @return The avgWriteEps.
     */
    @java.lang.Override
    public long getAvgWriteEps() {
      return avgWriteEps_;
    }
    /**
     * <code>int64 avgWriteEps = 7;</code>
     * @param value The avgWriteEps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgWriteEps(long value) {
      
      avgWriteEps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgWriteEps = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgWriteEps() {
      
      avgWriteEps_ = 0L;
      onChanged();
      return this;
    }

    private long avgWriteBps_ ;
    /**
     * <code>int64 avgWriteBps = 8;</code>
     * @return The avgWriteBps.
     */
    @java.lang.Override
    public long getAvgWriteBps() {
      return avgWriteBps_;
    }
    /**
     * <code>int64 avgWriteBps = 8;</code>
     * @param value The avgWriteBps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgWriteBps(long value) {
      
      avgWriteBps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgWriteBps = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgWriteBps() {
      
      avgWriteBps_ = 0L;
      onChanged();
      return this;
    }

    private long avgWriteTps_ ;
    /**
     * <code>int64 avgWriteTps = 9;</code>
     * @return The avgWriteTps.
     */
    @java.lang.Override
    public long getAvgWriteTps() {
      return avgWriteTps_;
    }
    /**
     * <code>int64 avgWriteTps = 9;</code>
     * @param value The avgWriteTps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgWriteTps(long value) {
      
      avgWriteTps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgWriteTps = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgWriteTps() {
      
      avgWriteTps_ = 0L;
      onChanged();
      return this;
    }

    private long avgUploadBps_ ;
    /**
     * <code>int64 avgUploadBps = 10;</code>
     * @return The avgUploadBps.
     */
    @java.lang.Override
    public long getAvgUploadBps() {
      return avgUploadBps_;
    }
    /**
     * <code>int64 avgUploadBps = 10;</code>
     * @param value The avgUploadBps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgUploadBps(long value) {
      
      avgUploadBps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgUploadBps = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgUploadBps() {
      
      avgUploadBps_ = 0L;
      onChanged();
      return this;
    }

    private long avgDumpBps_ ;
    /**
     * <code>int64 avgDumpBps = 11;</code>
     * @return The avgDumpBps.
     */
    @java.lang.Override
    public long getAvgDumpBps() {
      return avgDumpBps_;
    }
    /**
     * <code>int64 avgDumpBps = 11;</code>
     * @param value The avgDumpBps to set.
     * @return This builder for chaining.
     */
    public Builder setAvgDumpBps(long value) {
      
      avgDumpBps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 avgDumpBps = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgDumpBps() {
      
      avgDumpBps_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object extInfo_ = "";
    /**
     * <code>string extInfo = 12;</code>
     * @return The extInfo.
     */
    public java.lang.String getExtInfo() {
      java.lang.Object ref = extInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extInfo = 12;</code>
     * @return The bytes for extInfo.
     */
    public com.google.protobuf.ByteString
        getExtInfoBytes() {
      java.lang.Object ref = extInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extInfo = 12;</code>
     * @param value The extInfo to set.
     * @return This builder for chaining.
     */
    public Builder setExtInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extInfo = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtInfo() {
      
      extInfo_ = getDefaultInstance().getExtInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string extInfo = 12;</code>
     * @param value The bytes for extInfo to set.
     * @return This builder for chaining.
     */
    public Builder setExtInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dumper.FullMasterStatus)
  }

  // @@protoc_insertion_point(class_scope:dumper.FullMasterStatus)
  private static final com.alibaba.polardbx.rpc.cdc.FullMasterStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alibaba.polardbx.rpc.cdc.FullMasterStatus();
  }

  public static com.alibaba.polardbx.rpc.cdc.FullMasterStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FullMasterStatus>
      PARSER = new com.google.protobuf.AbstractParser<FullMasterStatus>() {
    @java.lang.Override
    public FullMasterStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FullMasterStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FullMasterStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FullMasterStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alibaba.polardbx.rpc.cdc.FullMasterStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

